name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev
        make

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: build/release/kanai
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}