name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Gradle Build
      run: |
        echo VERSION=$(gradle -q properties | grep 'version:' | cut -d ' ' -f 2) >> $GITHUB_ENV
        gradle build jpackage
        ls

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: Kanai-${{ env.VERSION }}.deb
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}