name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: MacOS
    runs-on: macos-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

    - name: Build
      run: make

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: build/release/kanai
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}