name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: MacOS
    runs-on: macos-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ make
        mv build/kanai kanai-macos
        echo VERSION=$(./kanai-macos -v | cut -d ' ' -f 2) >> $GITHUB_ENV

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: kanai-macos
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}