name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: MacOS
    runs-on: macos-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Make
      run: |
        echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
#       make

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}