name: Windows

on: workflow_dispatch

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Gradle Build
      run: |
        echo VERSION=$(./gradlew.bat -q properties | grep 'version:' | cut -d ' ' -f 2) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        ./gradlew.bat build dist

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: package/*.exe
        tag_name: v${{ env.VERSION }}
        fail_on_unmatched_files: true
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}