name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build Yarn
      run: |
        echo VERSION=$(node -p require('./package.json').version) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        yarn install

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}