name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
  
    - name: Checkout GitHub
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        make
        mv build/Release/kanai.exe kanai-windows.exe
        echo VERSION=$(./kanai-windows.exe -v | cut -d ' ' -f 2) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: kanai-windows.exe
        tag_name: v${{ env.VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}